### ISSUE TITLE
Flag Documentation [WIP]

### ISSUE THREAD

**Issue by allejo** [BZFlag-Dev/bzflag.org#3]
Here's an authoritative list of the flags that need documentation that still needs to be written. If you'd like to help us out with writing documentation and not waste time with possible conflicts with other people, post a comment here on which ones you'd like to write.

The flag documentation can be found at [_documentation/user/flags](https://github.com/BZFlag-Dev/bzflag.org/tree/redesign/_documentation/user/flags) on the `redesign` branch. See our [Contributing page](https://github.com/BZFlag-Dev/bzflag.org/wiki/Contributing) to learn about how to get started.

This issue will be updated as PRs and new commits are made.

- [x] agility fae0740fd31abffe18d243485bdab3d1240dc000
- [x] blindness (#5)
- [x] bouncy (#5)
- [x] burrow bf280732f8c08c4d43ec94f1394379b7754e56ff
- [x] cloaking f77dbe3d473cd93ab68ee8cc8442054e0d24ebb3
- [x] colorblindness (#5)
- [x] forward-only (#5)
- [x] genocide ffe72afdf2103d94e9a1ddaf5bc9f9b962d463e6
- [x] guided-missile 9ac7650f6fc83587c359ca302bba8f1f5502c58e
- [x] identify (#15)
- [x] invisible-bullet 633926536dd69ad267c5ebb9456444daf396d9ff
- [x] jamming (#5)
- [x] jumping (#10)
- [x] laser 5ae8f663d99191629613790802c3a6e9fb04b238
- [x] left-turn-only (#5)
- [x] machine-gun e11228392f4f431e6f8cf0447eeaf50f8718208c
- [x] masquerade d55ae22f608d54af120099bc301cb3cdfc22e337
- [x] momentum (#5)
- [x] narrow 8bcfcf3ca35754821082623068c77aba0e4a64c0
- [x] no-jumping (#5)
- [x] obesity (#5)
- [x] oscillation-overthruster (#12)
- [x] phantom-zone (#11)
- [x] quick-turn
- [x] rapid-fire
- [x] reversecontrols (#5)
- [x] reverseonly (#5)
- [x] ricochet (#9)
- [x] right-turn-only (#5)
- [x] seer (#7)
- [x] shield
- [x] shock-wave 4c87e56661507d13811666b955b3cd7fbb98e154
- [x] stealth (#4)
- [x] steamroller (#4)
- [x] super-bullet (#20)
- [x] thief 4897cd196725f23538cfeaf7b8137ca6221c831c
- [x] tiny (#23)
- [x] trigger-happy (#5)
- [x] useless ee69bf15f1552d9b549a13e207a0d42e77705778
- [x] wide-angle (#5)
- [x] wings (#4)

/cc @Zehra @The-Noah @tainn1

**Comment by Zehra** [comment]
For now, I would like provide documentation on all bad flags.
I may later on request other flags, but currently I'll be focusing on bad flags.

Note: For others who are contributing, the following are 'bad flags':
* blindness
* bouncy
* colorblindness
* forward-only
* jamming
* left-turn-only
* momentum
* no-jumping
* obesity
* reversecontrols
* reverseonly
* right-turn-only
* trigger-happy
* wide-angle

**Comment by tainn1** [comment]
I will work on the good flags, starting with Wings. I won't reserve any besides it, so I won't block any other willing participants from contributing to the base, but I will eventually touch all of them.

**Comment by blast007** [comment]
The last flag has been documented.  There will still be some edits to make, but it's enough to close this issue.
